<?php

define("PRIVATE_KEY", "/key/gpwebpay-pvk.key");
define("PUBLIC_TEST_GP_KEY", "/key/gpe.signing_test.pem");
define("PUBLIC_PROD_GP_KEY", "/key/gpe.signing_prod.pem");
define("GP_TEST_URL", "https://test.3dsecure.gpwebpay.com/pgw/order.do");
define("GP_PRODUCTION_URL", "https://3dsecure.gpwebpay.com/pgw/order.do");
define("GP_RESPONSE", 'commerce_gpwebpay');
define("GP_LOGO", '/images/gpwebpay.jpg');

define("ADDINFO_VERSION", '5.0');


